x<-read.table("/users/Punam/Downloads/household_power_consumption.txt",header=TRUE,sep=";",colClasses=c("character","character",rep("numeric",7)),na.strings="?")
y<-subset(x,Date=="1/2/2007" | Date=="2/2/2007")
datetime <- strptime(paste(y$Date, y$Time, sep=""), "%d/%m/%Y %H:%M:%S") 
globalActivePower <- as.numeric(subSetData$Global_active_power)
png("plot3.png", width=480, height=480)
plot(datetime, y$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, y$Sub_metering_2, type="l", col="red")
lines(datetime, y$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()