x<-read.table("/users/Punam/Downloads/household_power_consumption.txt",header=TRUE,sep=";",colClasses=c("character","character",rep("numeric",7)),na.strings="?")
y<-subset(x,Date=="1/2/2007" | Date=="2/2/2007")
datetime <- strptime(paste(y$Date, y$Time, sep=""), "%d/%m/%Y %H:%M:%S") 
globalActivePower <- as.numeric(subSetData$Global_active_power)
globalActivePower <- as.numeric(y$Global_active_power)
png("plot2.png", width=480, height=480)
plot(datetime, globalActivePower, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()